FROM node:20.6-alpine as base

WORKDIR /app

COPY package*.json ./

# RUN npm install && npm install --dev

COPY . .

RUN chmod 777 ./run.sh

# ENTRYPOINT ["sh", "run.sh"]
CMD ["tail", "-f", "/dev/null"]




